### ISSUE TITLE
 auto rotate

### ISSUE THREAD

**Issue by lijian-1994** [wkentaro/labelme#232]
when i use labelme to open pictures,some will be auto rotate.why?who can help me?

**Comment by wkentaro** [comment]
Maybe it is related to the EXIF, but not sure how to fix at this time. I put some links below related to this issue.
- https://photo.stackexchange.com/questions/84292/if-an-image-is-rotated-losslessly-why-does-the-file-size-change
- https://stackoverflow.com/questions/13872331/rotating-an-image-with-orientation-specified-in-exif-using-python-without-pil-in

**Comment by wkentaro** [comment]
Could you give me an example image to reproduce this?

**Comment by ramakrishna1592** [comment]
Can there be an option to rotate the image by 90 deg clockwise or anticlockwise.

**Comment by kaolin** [comment]
I've run into this as an EXIF issue. In my processes I've found stripping/correcting the source images is most reliable because you need to make sure that EVERY tool in your system handles EXIF correctly... and invariably, someone/something doesn't. :/ Stackexchange answer looks good.

Adding an option to rotate the image gets wonky...you really don't want to add in a "secondary" EXIF property. Maybe a purely interface rotation would be alright? But I don't think that would be good until the EXIF was properly respected, or you're going to have to "unfix" your data...

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can remove the EXIF orientation flags from images and convert images to the front orientation. If necessary, you can rotate the image right/left by 90 degrees.
https://rectlabel.com/help#remove_exif_orientation_flags
