### ISSUE TITLE
Duplicate rectangle between file with use next and prev

### ISSUE THREAD

**Issue by pprados** [wkentaro/labelme#266]
If you want to update some labelme files, with 
labelme --nodata --autosave \
  --labels faurecia/yolo/classes.txt \
  --flags faurecia/yolo/flags.txt \
  --validatelabel exact \
  datasets/

and if you move same rectangle and select next/prev between each move, the rectangle are merge in the labelme files

To test:
1 - create to labelme files
2 - exit
3 - restart
4 - add or move rectangle from one file
5 - go to next file => new rectangle are added
6 - prev/next many times...

I think it's a bug when the previous shape was automaticaly added to the next file

**Comment by wkentaro** [comment]
I can't reproduce this.
Have you checked the config file at $HOME/.labelmerc and if the flag keep_prev is false?
If it is true, this kind of behavior happens.

**Comment by pprados** [comment]
Hello,

Yes, the keep_prev was set. I think, the program can remember where the
keep_prev was applied, or applied only when create a new file.

Regards


Philippe Prados


Le dim. 2 déc. 2018 à 15:31, Kentaro Wada <notifications@github.com> a
écrit :

**Comment by IlyaOvodov** [comment]
If keep_prev is On, this behaviour seems to be by design. If you draw some labels and move to image without labeling, they are duplicated. If next image has labels, these labels are displayed, nothing is copied.
Did you encountered case when previous and current labels are mixed? I couldn't reproduce it.
