### ISSUE TITLE
Polygon label list causes missing objects (bug reported)

### ISSUE THREAD

**Issue by rocklinsuv** [wkentaro/labelme#347]
Hi there, I think I might have discovered a bug related to label list. If we don't sort the list accordingly, some labelled objects will be gone in the generated VOC-type files. For instance, if object A is within object B, you have to put A at the end of the list, so as to make A appear on the final VOC-like image.
Please refer to the "Polygon label" section and see the difference:

![2019-03-15 16-10-39屏幕截图](https://user-images.githubusercontent.com/7424627/54417868-4bfe1d00-473e-11e9-918a-1a26a2bc0e66.png)
![2019-03-15 16-12-35屏幕截图](https://user-images.githubusercontent.com/7424627/54417870-4bfe1d00-473e-11e9-91bc-2b80d961c1ef.png)

**Comment by rocklinsuv** [comment]
So I guess at least for now if you don't want to sort the list manually, always label the large object first, then label the small ones sitting inside the large one, then the small object labels will always be added to the end of the polygon label list.

**Comment by wkentaro** [comment]
Actually, this is the expected behavior of labelme, because there is no way to handle the overlap of different classes in VOC-type data export.
If you want to handle that cases, you need to use COCO-type data export.
https://github.com/wkentaro/labelme/blob/master/examples/instance_segmentation/labelme2coco.py
