### ISSUE TITLE
how could i label ring ?why not add a  painting brush tool?

### ISSUE THREAD

**Issue by bj5546** [wkentaro/labelme#396]

**Comment by wkentaro** [comment]
Because this is a polygon-based annotation tool, not painting-based.

I annotate donut-like shapes as below:

<img src=https://user-images.githubusercontent.com/4310419/57608134-584afe80-7564-11e9-87c1-3c89196eccb9.png width=30% />

**Comment by wkentaro** [comment]
For brushing annotation, maybe you can try https://github.com/yuyu2172/image-labelling-tool

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can label pixels using brushes and superpixels.
If necessary, you can convert the pixels mask to polygons and export to the Labelme JSON format.
https://rectlabel.com/help#create_pixels

We can send you a promotion code for RectLabel Pro so that you can download it for free.
If you could write a blog post or cite RectLabel on a research paper, it would be very helpful for us.
If you need the promotion code, send an email to support@rectlabel.com.

![brush](https://user-images.githubusercontent.com/1954306/214542752-2e34c406-bb88-4061-9eed-bc6c2968509d.jpg)
