### ISSUE TITLE
Feature request: full semantic segmentation brush tool

### ISSUE THREAD

**Issue by EricaMoreira** [wkentaro/labelme#426]
Thank you for all of the work you do! 

Do you have any plans to add a brush tool (with adjustable brush size)? Or a superpixel annotation tool (with adjustable superpixel size)? 

These tools are necessary for the annotation of medical images, and I am seeing them more in other image annotation GUIs (for example [RectLabel](https://rectlabel.com/) and [Supervisely](https://supervise.ly/)). These other GUIs are not open source, however, so I would very much prefer to use your tool.

**Comment by wkentaro** [comment]
I don't have any concrete plan on this, I will add this feature if it becomes a required feature for me.
Maybe you can try this open-source super-pixel-based annotation tool https://github.com/yuyu2172/image-labelling-tool, which a friend of mine created.

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can label pixels using brushes and superpixels.
If necessary, you can convert the pixels mask to polygons and export to the Labelme JSON format.
https://rectlabel.com/help#create_pixels

We can send you a promotion code for RectLabel Pro so that you can download it for free.
If you could write a blog post or cite RectLabel on a research paper, it would be very helpful for us.
If you need the promotion code, send an email to support@rectlabel.com.

![brush](https://user-images.githubusercontent.com/1954306/214542752-2e34c406-bb88-4061-9eed-bc6c2968509d.jpg)
