### ISSUE TITLE
how to use "flags" label ?

### ISSUE THREAD

**Issue by dlml** [wkentaro/labelme#469]

**Comment by wkentaro** [comment]
I’m not sure what do you mean by “flags” label.

**Comment by wkentaro** [comment]
For image-level flags, you can see this example. 
https://github.com/wkentaro/labelme/tree/master/examples/classification

**Comment by AlpAribal** [comment]
It also took me some time to figure out how to label images. It turns out you first need to create a .txt file that includes all possible labels (see [here](https://github.com/wkentaro/labelme/blob/master/examples/classification/flags.txt) for an example). Afterward, you need to run the command in the classification tutorial (`labelme data_annotated --flags flags.txt`), where `data_annotated` is the folder in which your images reside and `flags.txt` is the file you have just created.

**Comment by cm107** [comment]
I also have the same question.
There is a global "flags" key in every labelme json file, and another "flags" key under every shape label.
![image](https://user-images.githubusercontent.com/48467759/71940413-9387f500-31f9-11ea-9931-4bdc5b68c56e.png)

However, there does not seem to be any way to add flags from within the UI.
There's just a blank Flags dialogue box with no way to interact with it.
![image](https://user-images.githubusercontent.com/48467759/71940518-f2e60500-31f9-11ea-9142-189f0c4828d4.png)

@wkentaro これ、必要なくない？何のためにこれがjsonファイルに入っているのかはよくわからないのですが、使い方について説明して頂いてもいいでしょうか？

**Comment by wkentaro** [comment]
> There is a global "flags" key in every labelme json file, and another "flags" key under every shape label.
However, there does not seem to be any way to add flags from within the UI.
There's just a blank Flags dialogue box with no way to interact with it.

Global "flags" key is for **image-level** flags, and the "flags" key under shape labels is **shape-level** flags.
Actually, there is no way to add new flags from GUI, and you need to specify labels by command-line arguments as in the example:
https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation#annotation

**Comment by wkentaro** [comment]
In summary,

for **image-level flags**, please refer to https://github.com/wkentaro/labelme/tree/master/examples/classification#usage

for **shape-level flags**, please refer to https://github.com/wkentaro/labelme/tree/master/examples/instance_segmentation#annotation
