### ISSUE TITLE
bezier curve or x-spline polygons?

### ISSUE THREAD

**Issue by iperov** [wkentaro/labelme#622]
it would be good 
if you add bezier curve or x-spline polygons

**Comment by wkentaro** [comment]
But why? Because it looks fancier?

**Comment by julienguegan** [comment]
> But why? Because it looks fancier and smoother? You can apply any smoothing methods after the annotation process, right?

I also think that bezier curve would be quite interesting to have ... Not because it looks fancier but it would be much more efficient for the labellisation when you have round object or object with curve (which is quite often actually in real life). Currently when you want to annotate a curve you have to follow the curve and click as much as point are necessary. Bezier curve would allow to just click at each extremities and then control the shape by dragging your mouse where you want. So it would be faster and more precise. 

Find below the idea

![bezier_curve_example](https://user-images.githubusercontent.com/45081450/95974303-18e9a700-0e15-11eb-9236-2e8591f54aab.gif)

**Comment by ckolluru** [comment]
+1 for this idea - it would be immensely helpful in annotating medical images. 

It is not trivial to smooth a polygonal representation when there are multiple class labels touching each other.
