### ISSUE TITLE
[BUG] QT Error on Windows to Launch GUI

### ISSUE THREAD

**Issue by Zumbalamambo** [wkentaro/labelme#629]
QT Error

```
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by wkentaro** [comment]
Please provide information to reproduce (e.g., version, OS)

**Comment by Zumbalamambo** [comment]
@wkentaro Windows 10 and I'm using the latest version

**Comment by wkentaro** [comment]
I don't have Windows OS, so hope there's someone who can fix this.

**Comment by XiaoXiao-Woo** [comment]
I have also QT Error, but evering is ok in my another conda env, cloned from the same.

> [INFO] __init__:get_config:71 - Loading config file from: C:\Users\woo\.labelmerc
[WARNING] __init__:update_dict:17 - Skipping unexpected key in config: add_point
[WARNING] __init__:update_dict:17 - Skipping unexpected key in config: edit_line_color
[WARNING] __init__:update_dict:17 - Skipping unexpected key in config: edit_fill_color
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".
Reinstalling the application may fix this problem.

**Comment by XiaoXiao-Woo** [comment]
> I have also QT Error in windows10, but evering is ok in my another conda env, cloned from the same.
> 
> > [INFO] **init**:get_config:71 - Loading config file from: C:\Users\woo.labelmerc
> > [WARNING] **init**:update_dict:17 - Skipping unexpected key in config: add_point
> > [WARNING] **init**:update_dict:17 - Skipping unexpected key in config: edit_line_color
> > [WARNING] **init**:update_dict:17 - Skipping unexpected key in config: edit_fill_color
> > This application failed to start because it could not find or load the Qt platform plugin "windows"
> > in "".
> > Reinstalling the application may fix this problem.
