### ISSUE TITLE
Enhancement: Configuration or global setting to turn off Save With Image Data?

### ISSUE THREAD

**Issue by mattroos** [wkentaro/labelme#846]
As far as I can tell, there is no way to start labelme with ```Save With Image Data``` set to off/no. Am I wrong? Is there a command line option to do this, or a setting in the config file (.labelmerc)?

**Comment by Heermosi** [comment]
There is a way to set the save with image data file
If you look at the source code of the label me  you'll find it was closely connected with its initial configurations

```
        saveWithImageData = action(
            text=locale.ActionSaveWithImageDataToggle,
            slot=self.enableSaveImageWithData,
            tip=locale.ActionSaveWithImageDataToggleTip,
            checkable=True,
            checked=self._config["store_data"],
        )

```
so that the "store_data" would implicily indicate how it works on app load.
you may also look into the source folder to find it

`default_config.yaml
`
It may be lying in "Programs\Python\Python37\Lib\site-packages\labelme\config" on Windows 
Or "/usr/local/python37/Lib/site-packages/labelme/config" on Linux

When you find this file you may look for "store_data" and change it to false. Do the same to the labelme.rc.
And specially, on windows, the configuration is actually stored in registry, you must delete the registry entry totally before you can reload the default configurations.

Here is the default configraion registry key:

`HKEY_CURRENT_USER\Software\labelme\labelme
`

I'm currently working on this software and found some bugs to fix. Well, is it free of charge to edit and re-distribute the software?

**Comment by wkentaro** [comment]
There are 2 solutions:
1) Edit ~/.labelmerc and change `store_data: false`
2) `labelme --nodata`
