### ISSUE TITLE
[QUESTION] Labeling the background

### ISSUE THREAD

**Issue by abderhasan** [wkentaro/labelme#899]
When I want to label an _object_, I draw a polygon around that object and give it a class name (label).

For the _background_, would that be any unlabeled object in the image, which would also be assigned the label `_background_`?

Thanks.

**Comment by wkentaro** [comment]
It's kind of all up to you and how you implement the parse script of the JSON files.
But if you're using `examples/semantic_segmentation/labelme2voc.py`, yes that's how it deals with unlabeled regions.

**Comment by EMCP** [comment]
it seems in my current model, they expect the background to be `__background__` .. I missed where this gets injected in either labelme or labelme2coco ...

is it customized in labelme2coco afterall ?

I can see in `labels.txt` I needed `__ignore__` .. I guess I can change this to `__background__` because it is the same to labelme?

Thank you
